### PR TITLE
Remove product from CMIP6Plus_required_global_attributes.json

### PR DESCRIPTION
**Pull request by matthew-mizielinski**

### CODE REVIEW

**Comment by durack1** [comment]
@matthew-mizielinski I am not certain of the status of the automation. If I approve this, would it just get processed by github actions? I suppose this is a question for @wolfiex

**Comment by matthew-mizielinski** [comment]
> @matthew-mizielinski I am not certain of the status of the automation. If I approve this, would it just get processed by github actions? I suppose this is a question for @wolfiex

That's why I put this in draft -- The automation has generated [CMIP6Plus_CV.json](https://github.com/WCRP-CMIP/CMIP6Plus_CVs/blob/be09abb1b2720ab8e4243b1094c06805d8007e21/CVs/CMIP6Plus_CV.json) allowing @mauzey1 to proceed with the CMOR update, and @wolfiex can let us know if anything else is needed prior to merge & release

**Comment by wolfiex** [comment]
If it doesn't update you can re-enable the actions from the actions tab, or run the CV creation script from the .github repository. 

Unfortunately I dont have a laptop with me this week to check myself.

**Comment by wolfiex** [comment]
Currently everything should work - I just plan on redoing the version metadata action triggers / checks . The format will be the same.

**Comment by durack1** [comment]
> Currently everything should work - I just plan on redoing the version metadata action triggers / checks . The format will be the same.

Great, we'll merge ahead and we can clean anything up after the fact anyway - it's all versioned!

**Pull request merged**
