### PR TITLE
Combined source_id pull requests

### PR DESCRIPTION
**Pull request by wolfiex**
This should be a merge of all the pull requests.   Merge __*not to squash*__ the commits - I will tidy the chain up later.

### CODE REVIEW

**Review by matthew-mizielinski — APPROVED** [review]
Looks good from a quick inspection and I've confirmed they are all valid JSON. If you want to wait for confirmation that CMOR is happy with them I'll try some CMOR tests next week if you can provide the updated CV.json file.

Approving on the assumption that header metadata will be appropriately updated.

**Comment by durack1** [comment]
@mauzey1 is there a way to check that CMOR is happy with these tweaks? I note you're getting very close to having most of the 3.8.0 issues solved

**Comment by mauzey1** [comment]
@durack1 
I'm currently in the process of trying to remove `product` from global attributes in CMOR.

I'm going to update https://github.com/PCMDI/cmor/issues/723 discussing how we could remove the `product` attribute.

**Comment by durack1** [comment]
@mauzey1 great - there is work happening across repos in parallel, so just wanted to make sure we're as synced as can make sense

**Pull request merged**
